name: Deploy to WikiTree Apps

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run cy:start-and-run
    - run: npm run deploy-wikitree
      env:
        LFTP_PASSWORD: ${{ secrets.WIKITREE_PASSWORD }}
